module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'jsdom',
  setupFiles: ['<rootDir>/jest.setup.js'],
  moduleFileExtensions: ['js', 'ts', 'json', 'vue'],
  transform: {
    '^.+\\.js$': 'babel-jest',
    '^.+\\.vue$': '@vue/vue2-jest',
  },
  moduleNameMapper: {
    '\\.(css|scss|sass)$': '<rootDir>/test-unit/mocks/styleMock.js',
    '\\.(svg|png|jpg|jpeg|gif|webp)$': '<rootDir>/test-unit/mocks/fileMock.js',
    '^~/(.*)$': '<rootDir>/$1',
    '^@/(.*)$': '<rootDir>/$1',
  },
  testMatch: ['<rootDir>/test-unit/**/*.spec.js'],
  snapshotSerializers: ['<rootDir>/node_modules/jest-serializer-vue'],
  collectCoverageFrom: [
    '**/*.{js,jsx,ts,tsx,vue}',
    '!**/node_modules/**',
    '!**/.nuxt/**',
    '!**/@types/**',
    '!**/.eslintrc.js',
    '!**/nuxt.config.js',
    '!**/jest.config.js',
    '!**/nuxt-i18n.config.js',
    '!**/nuxt-router-override-sample.config.js',
    '!**/tests/**',
    '!**/coverage/**',
  ],
};
